spring:
  application:
    name: kotlin_spring_playground

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  playground:
    enabled: false
  voyager:
    enabled: true
  graphiql:
    enabled: true

server:
  port: 8000