inputTransformers:
  discord_send_message:
    - noOpTransformer
webRequestTransformers:
  discord_send_message:
    - noOpTransformer
outputTransformers:
  discord_send_message:
    - discordMessagePreprocessor
    - discordMessageFormatter
    - discordMessageValidator
