outputTransformers:
  send_discord_message:
    - discordMessagePreprocessor
    - discordMessageFormatter
    - discordMessageValidator
inputTransformers:
  send_discord_message:
    - noOpTransformer