outputTransformers:
  discord_send_message:
    - discordMessagePreprocessor
    - discordMessageFormatter
    - discordMessageValidator
inputTransformers:
  discord_send_message:
    - noOpTransformer