inputTransformers:
  SLACK_MESSAGE:
    - slackInputPreprocessor
    - slackInputFormatter
    - slackInputValidator
  EMAIL_MESSAGE:
    - emailPreprocessor
    - emailFormatter
    - emailValidator
webRequestTransformers:
  SLACK_MESSAGE:
    - slackWebRequestPreprocessor
  EMAIL_MESSAGE:
    - noOpTransformer
outputTransformers:
  SLACK_MESSAGE:
    - slackMessagePreprocessor
    - slackMessageFormatter
    - slackMessageValidator
  EMAIL_MESSAGE:
    - emailPreprocessor
    - emailFormatter
    - emailValidator
