outputTransformers:
  SLACK_MESSAGE:
    - slackMessagePreprocessor
    - slackMessageFormatter
    - slackMessageValidator
  EMAIL_MESSAGE:
    - emailPreprocessor
    - emailFormatter
    - emailValidator
inputTransformers:
  SLACK_MESSAGE:
    - slackInputPreprocessor
    - slackInputFormatter
    - slackInputValidator
  EMAIL_MESSAGE:
    - emailPreprocessor
    - emailFormatter
    - emailValidator